repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
    - id: check-merge-conflict
    - id: debug-statements

#-   repo: https://github.com/asottile/seed-isort-config
#    rev: v1.9.2
#    hooks:
#    -   id: seed-isort-config
#        args: [--application-directories=rental core]
#
#-   repo: https://github.com/pre-commit/mirrors-isort
#    rev: v4.3.21
#    hooks:
#    -   id: isort
#        language_version: python3.7

-   repo: https://github.com/ambv/black
    rev: 19.3b0
    hooks:
    - id: black
      language_version: python3.7
